FROM node:25-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
WORKDIR /usr/src/app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter api build

FROM base AS runner
RUN apk add --no-cache python3 py3-pip tesseract-ocr poppler-utils build-base jpeg-dev zlib-dev
WORKDIR /usr/src/app
COPY --from=build /usr/src/app /usr/src/app
RUN python3 -m venv .venv && .venv/bin/pip install --upgrade pip && .venv/bin/pip install -r python/requirements.txt
EXPOSE 8000
CMD ["pnpm", "--filter", "api", "start:prod"]
